app = "usg-platform"
primary_region = "lhr"  # London region, change as needed

[build]
  image = "usg-platform"

[env]
  PYTHONUNBUFFERED = "1"
  DJANGO_SETTINGS_MODULE = "ugc_platform.settings.production"

[deploy]
  strategy = "rolling"
  health_checks = [
    { port = 8080, type = "http", interval = "15s", timeout = "2s", grace_period = "5s", method = "get", path = "/health/", protocol = "http", tls_skip_verify = false }
  ]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
  protocol = "tcp"
  internal_port = 6379
  processes = ["redis"]

  [[services.ports]]
    port = 6379
    handlers = ["redis"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 5432
  processes = ["postgres"]

  [[services.ports]]
    port = 5432
    handlers = ["postgres"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[metrics]
  port = 9091
  path = "/metrics" 