# Generated by Django 4.2.7 on 2025-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ugc_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
