# Generated by Django 4.2.7 on 2025-03-30 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ugc_users", "0001_initial"),
    ]

    operations = []
