# Generated by Django 4.2.7 on 2025-03-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ugc_ai", "0001_initial"),
        ("ugc_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrecommendation",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="ugc_content.content",
            ),
        ),
    ]
