# Generated by Django 4.2.7 on 2025-03-30 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ugc_content", "0001_initial"),
        ("ugc_ai", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentdetection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentanalysis",
            name="content",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="ugc_content.content",
            ),
        ),
        migrations.AddField(
            model_name="contentanalysis",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ugc_ai.aimodel",
            ),
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(
                fields=["user", "recommendation_type"],
                name="ugc_ai_cont_user_id_8432a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentrecommendation",
            index=models.Index(
                fields=["created_at", "expires_at"],
                name="ugc_ai_cont_created_2f8b3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentdetection",
            index=models.Index(
                fields=["user", "platform"], name="ugc_ai_cont_user_id_aa6dc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentdetection",
            index=models.Index(fields=["status"], name="ugc_ai_cont_status_64d592_idx"),
        ),
    ]
